server:
  port: 8000

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        # 1. User Service
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**, /api/users/**, /api/admin/users/**, /users/**

        # 2. Salon Service
        - id: SALON-SERVICE
          uri: lb://SALON-SERVICE
          predicates:
            - Path=/salons/**, /api/salons/**, /api/admin/salons/**

        # 3. Payment Service
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**

        # 4. Booking Service
        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/booking/**

        # 5. Category Service
        - id: CATEGORY-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/categories/**

        # 6. Offering Service
        - id: OFFERING-SERVICE
          uri: lb://OFFERING-SERVICE
          predicates:
            - Path=/api/service-offering/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
