# =========================
# DOCKER COMPOSE FILE
# =========================
services:

  # =========================
  # DATABASES
  # =========================

  user_service_db:
    image: mysql:8
    container_name: user_service_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: user_service_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  salon_service_db:
    image: mysql:8
    container_name: salon_service_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: salon_service_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  payment_service_db:
    image: mysql:8
    container_name: payment_service_db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: payment_service_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  offering_service_db:
    image: mysql:8
    container_name: offering_service_db
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: offering_service_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  category_service_db:
    image: mysql:8
    container_name: category_service_db
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: category_service_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  booking_service_db:
    image: mysql:8
    container_name: booking_service_db
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: booking_service_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  # =========================
  # EUREKA SERVER
  # =========================
  eurekaserver:
    image: triquang15/eureka-server:v1
    container_name: eurekaserver
    ports:
      - "8070:8070"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://eurekaserver:8070/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  # =========================
  # MICROSERVICES
  # =========================
  userservice:
    image: triquang15/user-service:v1
    container_name: userservice
    environment:
      SPRING_APPLICATION_NAME: user-service
      SPRING_DATASOURCE_URL: jdbc:mysql://user_service_db:3306/user_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      EUREKA_INSTANCE_HOSTNAME: userservice
    ports:
      - "8080:8080"
    depends_on:
      - user_service_db
      - eurekaserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://userservice:8080/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  salonservive:
    image: triquang15/salon-service:v1
    container_name: salonservive
    environment:
      SPRING_APPLICATION_NAME: salon-service
      SPRING_DATASOURCE_URL: jdbc:mysql://salon_service_db:3306/salon_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      EUREKA_INSTANCE_HOSTNAME: salonservive
    ports:
      - "8081:8081"
    depends_on:
      - salon_service_db
      - eurekaserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://salonservive:8081/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  paymentservice:
    image: triquang15/payment-service:v1
    container_name: paymentservice
    environment:
      SPRING_APPLICATION_NAME: payment-service
      SPRING_DATASOURCE_URL: jdbc:mysql://payment_service_db:3306/payment_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      EUREKA_INSTANCE_HOSTNAME: paymentservice
    ports:
      - "8085:8085"
    depends_on:
      - payment_service_db
      - eurekaserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://paymentservice:8085/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  offeringservice:
    image: triquang15/offering-service:v1
    container_name: offeringservice
    environment:
      SPRING_APPLICATION_NAME: offering-service
      SPRING_DATASOURCE_URL: jdbc:mysql://offering_service_db:3306/offering_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      EUREKA_INSTANCE_HOSTNAME: offeringservice
    ports:
      - "8083:8083"
    depends_on:
      - offering_service_db
      - eurekaserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://offeringservice:8083/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  bookingservice:
    image: triquang15/booking-service:v1
    container_name: bookingservice
    environment:
      SPRING_APPLICATION_NAME: booking-service
      SPRING_DATASOURCE_URL: jdbc:mysql://booking_service_db:3306/booking_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      EUREKA_INSTANCE_HOSTNAME: bookingservice
    ports:
      - "8084:8084"
    depends_on:
      - booking_service_db
      - eurekaserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://bookingservice:8084/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  categoryservice:
    image: triquang15/category-service:v1
    container_name: categoryservice
    environment:
      SPRING_APPLICATION_NAME: category-service
      SPRING_DATASOURCE_URL: jdbc:mysql://category_service_db:3306/category_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      EUREKA_INSTANCE_HOSTNAME: categoryservice
    ports:
      - "8082:8082"
    depends_on:
      - category_service_db
      - eurekaserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://categoryservice:8082/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

  # =========================
  # GATEWAY
  # =========================
  gateway:
    image: triquang15/gateway-server:v1
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      SPRING_APPLICATION_NAME: gateway-server
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      # ====== ROUTES TO MICROSERVICES ======
      ROUTE_USER_SERVICE: lb://USER-SERVICE
      ROUTE_SALON_SERVICE: lb://SALON-SERVICE
      ROUTE_PAYMENT_SERVICE: lb://PAYMENT-SERVICE
      ROUTE_OFFERING_SERVICE: lb://OFFERING-SERVICE
      ROUTE_CATEGORY_SERVICE: lb://CATEGORY-SERVICE
      ROUTE_BOOKING_SERVICE: lb://BOOKING-SERVICE
    depends_on:
      - userservice
      - salonservive
      - paymentservice
      - offeringservice
      - categoryservice
      - bookingservice
      - eurekaserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://gateway:8000/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - salon-network

# =========================
# NETWORKS
# =========================
networks:
  salon-network:
    driver: bridge
